version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env.private
    environment:
      MODELS: >
        [
          {
            "name": "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
            "displayName": "DeepSeek-R1-Distill-Qwen-32B",
            "description": "由Deepseek R1蒸馏到Qwen-32B模型。",
            "modelUrl": "https://github.com/deepseek-ai/DeepSeek-R1",
            "websiteUrl": "https://deepseek.com/",
            "logoUrl": "https://llms.chat/chatui/deepseek-logo.png",
            "reasoning": {
              "type": "tokens",
              "beginToken": "<think>",
              "endToken": "</think>"
            },
            "promptExamples": [
              {
                "title": "9.11和9.9哪个大",
                "prompt": "9.11和9.9哪个大"
              },
              {
                "title": "测容量",
                "prompt": "我有2个 5 升和1个 12 升的罐子。我想精确测量 6 升."
              },
              {
                "title": "林黛玉倒拔垂杨柳",
                "prompt": "你知道林黛玉倒把垂杨柳的故事吗"
              }
            ],
            "endpoints": [
                {
                    "type": "openai",
                    "baseURL": "https://api-inference.huggingface.co/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B/v1",
                }
            ]
          },
          {
            "name": "deepseek-ai/DeepSeek-R1",
            "displayName": "DeepSeek R1",
            "description": "在后训练阶段大规模使用了强化学习技术，在仅有极少标注数据的情况下，极大提升了模型推理能力，尤其在数学、代码、自然语言推理等任务上。",
            "modelUrl": "https://github.com/deepseek-ai/DeepSeek-R1",
            "websiteUrl": "https://deepseek.com/",
            "logoUrl": "https://llms.chat/chatui/deepseek-logo.png",
            "reasoning": {
              "type": "tokens",
              "beginToken": "<think>",
              "endToken": "</think>"
            },
            "promptExamples": [
              {
                "title": "9.11和9.9哪个大",
                "prompt": "9.11和9.9哪个大"
              },
              {
                "title": "测容量",
                "prompt": "我有2个 5 升和1个 12 升的罐子。我想精确测量 6 升."
              },
              {
                "title": "林黛玉倒拔垂杨柳",
                "prompt": "你知道林黛玉倒把垂杨柳的故事吗"
              }
            ],
            "endpoints": [
                {
                    "type": "openai",
                    "baseURL": "https://api.siliconflow.cn/v1",
                    "apiKey": "${API_KEY}"
                }
            ]
          },
          {
            "name": "deepseek-ai/DeepSeek-V3",
            "displayName": "DeepSeek V3",
            "description": "由杭州深度求索人工智能基础技术研究有限公司自研的 MoE 模型，在百科知识、数学推理等多项任务上优势突出，评测成绩在主流榜单中位列开源模型榜首。",
            "modelUrl": "https://github.com/deepseek-ai/DeepSeek-R1",
            "websiteUrl": "https://deepseek.com/",
            "logoUrl": "https://llms.chat/chatui/deepseek-logo.png",
            "reasoning": {
              "type": "tokens",
              "beginToken": "<think>",
              "endToken": "</think>"
            },
            "promptExamples": [
              {
                "title": "9.11和9.9哪个大",
                "prompt": "9.11和9.9哪个大"
              },
              {
                "title": "测容量",
                "prompt": "我有2个 5 升和1个 12 升的罐子。我想精确测量 6 升."
              },
              {
                "title": "林黛玉倒拔垂杨柳",
                "prompt": "你知道林黛玉倒把垂杨柳的故事吗"
              }
            ],
            "endpoints": [
                {
                    "type": "openai",
                    "baseURL": "https://api.siliconflow.cn/v1",
                    "apiKey": "${API_KEY}"
                }
            ]
          },
          {
            "name": "Qwen/Qwen2.5-72B-Instruct",
            "tokenizer": "Qwen/Qwen2.5-72B-Instruct",
            "description": "The latest Qwen open model with improved role-playing, long text generation and structured data understanding.",
            "modelUrl": "https://huggingface.co/Qwen/Qwen2.5-72B-Instruct",
            "websiteUrl": "https://qwenlm.github.io/blog/qwen2.5/",
            "logoUrl": "https://llms.chat/chatui/qwen-logo.png",
            "preprompt": "You are Qwen, created by Alibaba Cloud. You are a helpful assistant.",
            "parameters": {
              "stop": ["<|endoftext|>", "<|im_end|>"],
              "temperature": 0.6,
              "truncate": 28672,
              "max_new_tokens": 3072
            },
            "promptExamples": [
              {
                "title": "Write an email from bullet list",
                "prompt": "As a restaurant owner, write a professional email to the supplier to get these products every week: \n\n- Wine (x10)\n- Eggs (x24)\n- Bread (x12)"
              },
              {
                "title": "Code a snake game",
                "prompt": "Code a basic snake game in python, give explanations for each step."
              },
              {
                "title": "Assist in a task",
                "prompt": "How do I make a delicious lemon cheesecake?"
              }
            ]
          },
          { 
            "name" : "meta-llama/Meta-Llama-3.1-70B-Instruct",
            "id": "meta-llama/Meta-Llama-3.1-70B-Instruct",
            "tokenizer": {"tokenizerUrl": "https://huggingface.co/nsarrazin/llama3.1-tokenizer/resolve/main/tokenizer.json", "tokenizerConfigUrl": "https://huggingface.co/nsarrazin/llama3.1-tokenizer/raw/main/tokenizer_config.json"},
            "description": "Ideal for everyday use. A fast and extremely capable model matching closed source models' capabilities.",
            "modelUrl": "https://huggingface.co/meta-llama/Meta-Llama-3.1-70B-Instruct",
            "websiteUrl": "https://llama.meta.com/",
            "logoUrl": "https://llms.chat/chatui/meta-logo.png",
            "tools": true,
            "preprompt" : "",
            "parameters": {
                "temperature": 0.6,
                "top_p": 0.9,
                "stop": ["<|endoftext|>", "<|eot_id|>"],
              "max_new_tokens": 1024,
              "truncate": 7167
            },
            "promptExamples": [
              {
                "title": "Translate a contract clause",
                "prompt": "Translate the following legal clause from Chinese to English: \n\n- 本合同自双方签字盖章后生效，任何一方不得单方面变更合同条款。"
              }, 
              {
                "title": "Plan a marketing campaign",
                "prompt": "As a social media manager, create a 3-month marketing campaign plan for a new tech product launch, including content ideas, platforms, and budget considerations."
              }, 
              {
                "title": "写作短篇故事",
                "prompt": "写一个以友情为主题的500字短篇故事，包含一个意想不到的结局。"
              }
            ]
          }, 
          {
            "name" : "CohereForAI/c4ai-command-r-plus-08-2024",
            "tokenizer": {"tokenizerUrl": "https://huggingface.co/nsarrazin/c4ai-command-r-v01-tokenizer/resolve/main/tokenizer.json", "tokenizerConfigUrl": "https://huggingface.co/nsarrazin/c4ai-command-r-v01-tokenizer/raw/main/tokenizer_config.json"},
            "description": "Cohere's largest language model, optimized for conversational interaction and tool use. Now with the 2024 update!",
            "modelUrl": "https://huggingface.co/CohereForAI/c4ai-command-r-plus-08-2024",
            "websiteUrl": "https://docs.cohere.com/docs/command-r-plus",
            "logoUrl": "https://llms.chat/chatui/cohere-logo.png",
            "tools": true,
            "parameters": {
              "stop": ["<|END_OF_TURN_TOKEN|>"],
              "truncate" : 28672,
              "max_new_tokens" : 2048,
              "temperature" : 0.3
            },
            "promptExamples" : [
              {
                "title": "生成产品广告文案",
                "prompt": "为一款新发布的智能手表撰写一段吸引用户的广告文案，突出其健康监测功能和时尚设计。"
              }, 
              {
                "title": "解释复杂概念",
                "prompt": "用简单易懂的语言解释量子计算的基本原理，并举例说明其可能的应用场景。"
              }, 
              {
                "title": "编写数据分析代码",
                "prompt": "用Python编写一个数据分析脚本，读取CSV文件中的销售数据，计算每个月的总销售额，并生成可视化图表。"
              }
            ]
          },
          {
            "name": "microsoft/Phi-3-mini-4k-instruct",
            "tokenizer": "microsoft/Phi-3-mini-4k-instruct",
            "description" : "One of the best small models (3.8B parameters), super fast for simple tasks.",
            "logoUrl": "https://llms.chat/chatui/microsoft-logo.png",
            "modelUrl": "https://huggingface.co/microsoft/Phi-3-mini-4k-instruct",
            "websiteUrl": "https://azure.microsoft.com/en-us/blog/introducing-phi-3-redefining-whats-possible-with-slms/",
            "preprompt": "",
            "parameters": {
              "stop": ["<|end|>", "<|endoftext|>", "<|assistant|>"],
              "temperature": 0.7,
              "max_new_tokens": 1024,
              "truncate": 3071
            },
            "promptExamples": [
              {
                "title": "Write an email from bullet list",
                "prompt": "As a restaurant owner, write a professional email to the supplier to get these products every week: \n\n- Wine (x10)\n- Eggs (x24)\n- Bread (x12)"
              }, {
                "title": "Code a snake game",
                "prompt": "Code a basic snake game in python, give explanations for each step."
              }, {
                "title": "Assist in a task",
                "prompt": "How do I make a delicious lemon cheesecake?"
              }
            ]
          }
        ]
      TOOLS: >
        [
          {
            "_id": "000000000000000000000001",
            "displayName": "Image Generation",
            "description": "Use this tool to generate images based on a prompt.",
            "color": "yellow",
            "icon": "camera",
            "baseUrl": "black-forest-labs/FLUX.1-schnell",
            "name": "image_generation",
            "endpoint": "/infer",
            "inputs": [
              {
                "name": "prompt",
                "description": "A prompt to generate an image from",
                "paramType": "required",
                "type": "str"
              },
              { "name": "seed", "paramType": "fixed", "value": "0", "type": "float" },
              {
                "name": "randomize_seed",
                "paramType": "fixed",
                "value": "true",
                "type": "bool"
              },
              {
                "name": "width",
                "description": "numeric value between 256 and 2048",
                "paramType": "optional",
                "default": 1024,
                "type": "float"
              },
              {
                "name": "height",
                "description": "numeric value between 256 and 2048",
                "paramType": "optional",
                "default": 1024,
                "type": "float"
              },
              {
                "name": "num_inference_steps",
                "paramType": "fixed",
                "value": "4",
                "type": "float"
              }
            ],
            "outputComponent": "image",
            "outputComponentIdx": 0,
            "showOutput": true
          },
          {
            "_id": "000000000000000000000002",
            "displayName": "Document Parser",
            "description": "Use this tool to parse any document and get its content in markdown format.",
            "color": "yellow",
            "icon": "cloud",
            "baseUrl": "huggingchat/document-parser",
            "name": "document_parser",
            "endpoint": "/predict",
            "inputs": [
              {
                "name": "document",
                "description": "Filename of the document to parse",
                "paramType": "required",
                "type": "file",
                "mimeTypes": 'application/*'
              },
              {
                "name": "filename",
                "paramType": "fixed",
                "value": "document.pdf",
                "type": "str"
              }
            ],
            "outputComponent": "textbox",
            "outputComponentIdx": 0,
            "showOutput": false
          },
          {
            "_id": "000000000000000000000003",
            "name": "edit_image",
            "baseUrl": "multimodalart/cosxl",
            "endpoint": "/run_edit",
            "inputs": [
              {
                "name": "image",
                "description": "The image path to be edited",
                "paramType": "required",
                "type": "file",
                "mimeTypes": 'image/*'
              },
              {
                "name": "prompt",
                "description": "The prompt with which to edit the image",
                "paramType": "required",
                "type": "str"
              },
              {
                "name": "negative_prompt",
                "paramType": "fixed",
                "value": "",
                "type": "str"
              },
              {
                "name": "guidance_scale",
                "paramType": "fixed",
                "value": 6.5,
                "type": "float"
              },
              {
                "name": "steps",
                "paramType": "fixed",
                "value": 30,
                "type": "float"
              }
            ],
            "outputComponent": "image",
            "showOutput": true,
            "displayName": "Image Editor",
            "color": "green",
            "icon": "camera",
            "description": "This tool lets you edit images",
            "outputComponentIdx": 0
          }
        ]
      TEXT_EMBEDDING_MODELS: |
        [
          {
            "name": "Xenova/gte-small",
            "displayName": "Xenova/gte-small",
            "description": "Local embedding model running on the server.",
            "chunkCharLength": 512,
            "endpoints": [
              { "type": "transformersjs" }
            ]
          }
        ]
  mongo:
    image: mongo:latest
    container_name: mongo-chatui
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
    driver: local

# sudo docker compose --env-file .env.private up -d